<a href="https://colab.research.google.com/github/aot-abhishekyadav/Machine-Learning-Fundamentals/blob/main/13-Binning-and-Binarization/Binarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2. Binarization
Definition

Binarization converts numerical values into only 0 or 1 using a threshold.

Formula


           x =     {0, x≤Threshold
	​       x =     {1 , x > Threshold



	​

| Age | Output |
| --- | ------ |
| 18  | 0      |
| 25  | 0      |
| 31  | 1      |
| 40  | 1      |
| 55  | 1      |

e.g. yai hai ki agr tumhari age > 18 hai to 1 varana 0

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Titanic1.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [ ]:
df['family'] = df['SibSp'] + df['Parch']

In [ ]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [ ]:
df.sample(10)

       Age      Fare  Survived  family
305   0.92  151.5500         1       3
120  21.00   73.5000         0       2
24    8.00   21.0750         0       4
416  34.00   32.5000         1       2
169  28.00   56.4958         0       0
672  70.00   10.5000         0       0
856  45.00  164.8667         1       2
498  25.00  151.5500         0       3
174  56.00   30.6958         0       0
869   4.00   11.1333         1       2

In [ ]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.head()

      Age     Fare  family
328  31.0  20.5250       2
73   26.0  14.4542       1
253  30.0  16.1000       1
719  33.0   7.7750       0
666  25.0  13.0000       0

In [ ]:
# Without binarization

clf = DecisionTreeClassifier()

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_test,y_pred)

0.6223776223776224

In [ ]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.6485133020344287)

In [ ]:
# Applying Binarization

from sklearn.preprocessing import Binarizer
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [ ]:
pd.DataFrame(X_train_trf,columns=['family','Age','Fare'])

     family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [ ]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2 = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred2)

0.6153846153846154

In [ ]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

np.float64(0.633196400625978)