<a href="https://colab.research.google.com/github/aot-abhishekyadav/Machine-Learning-Fundamentals/blob/main/04-Pandas/api-to-dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import pandas as pd

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=849963220a6f88e826547024bdf9c95f&language=en-US&page=1')

In [ ]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [ ]:
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,91.4770,8.915,1889
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,159.3015,8.724,30709
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,182.9313,8.707,3343
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.6182,8.687,23125
4,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,162.3307,8.676,5797
5,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.2068,8.571,14019
6,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,25.4754,8.570,17578
7,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,24.7305,8.565,10095
8,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,22.8149,8.553,703
9,1383731,Protector,Nikki's life is shattered when her daughter is...,2026-02-20,19.7051,8.540,409
10,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,38.1207,8.535,18498
11,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,41.5566,8.532,36033
12,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,13.8505,8.510,4600
13,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,29.5859,8.506,19401
14,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,39.3488,8.500,26787
15,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,10.4954,8.500,355
16,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,31.7940,8.492,20832
17,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,37.3786,8.482,30376
18,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-07-01,27.4574,8.481,12670
19,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,65.4087,8.481,40226

In [ ]:
df = pd.DataFrame()

In [ ]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=849963220a6f88e826547024bdf9c95f&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [ ]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,91.4770,8.915,1889
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,159.3015,8.724,30709
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,182.9313,8.707,3343
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.6182,8.687,23125
4,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,162.3307,8.676,5797
...,...,...,...,...,...,...,...
8555,13168,Smiley Face,"Jane, a struggling but perpetually stoned actr...",2007-11-16,4.0814,6.042,332
8556,718400,The Vanished,A family vacation takes a terrifying turn when...,2020-08-21,2.7456,6.041,362
8557,549514,Fatale,"After a wild one-night stand, successful sport...",2020-12-18,2.4689,6.000,390
8558,429415,Extinction,"A chief mechanic at a factory, haunted by apoc...",2018-07-15,3.4258,6.041,2006
8559,345922,Fist Fight,"When one school teacher gets the other fired, ...",2017-02-16,2.3378,6.041,1320

In [ ]:
df.shape

(8560, 7)

In [ ]:
df.to_csv('Top_Rated_movies.csv')